m3u/parser.go
* Had problem with slow parse of m3u list, download timeout.
* Download full m3u file before parsing will solve download timeout.
1. Tested on different/size of m3u files.
=> Download before parse

README.md, mp4_handler.go
* Sometimes, we don't want to use the brute force method of load balancing. This method fills up one M3U connection first before trying out different M3Us. Having an option to use round-robin load balancing would be a good feature to have.
* Add a LOAD_BALANCING_MODE to prevent breaking changes for people who prefer the brute force method instead of just simply changing the algorithm.
=> Add LOAD_BALANCING_MODE to modify algorithm used

README.md, main_test.go, mp4_handler.go
* Intermittent connections do not resolve correctly as a "disconnect" state.
* Add a functionality to use a buffer when streaming.
=> Add BUFFER_MB functionality

mp4_handler.go
* Go’s http package doesn’t specify request timeouts by default, allowing a possibility of services hijacking goroutines.
* Cap the TCP connect and TLS handshake timeouts, as well as establishing an end-to-end request timeout.
=> Optimize HTTP timeout

README.md
* Corrected path for data persistent in docker-compose example and fix typo for SYNC_ON_BOOT in readme file.
* N/A
1. N/A
=> correct data path and fix typo

m3u/parser.go, mp4_handler.go, utils/env.go, utils/http.go
* USER_AGENT env var only applied for fetching the M3U files.
* Set USER_AGENT when fetching the actual streams as well.
* Create custom http request function to ensure headers are used.
=> Use USER_AGENT env var for the actual video streams

database/database_test.go, database/db.go, m3u/generate.go, m3u/m3u_test.go, m3u/parser.go, main.go, main_test.go, mp4_handler.go
* The current handling of databases can be a lot cleaner if each instance/connection will have its own mutex state.
* Create a separate struct for each database instance with separate mutex.
* Add a global `swappingLock` to make sure the playlist route will wait until database swap is finished.
* Add playlist route HTTP status test.
=> Optimize database instances

README.md, m3u/parser.go, main_test.go
* Include only selected channel groups to parse. Often lots of unwanted groups in playlist, taking time to parse.
* Just checking during parsing if channel groups should be included or not, default is all.
1. Test run on several huge playlists.
=> Groups include filter

database/db.go
* An SQLite database connection defaults to journal_mode=DELETE.
* WAL is significantly faster in most scenarios.
* WAL provides more concurrency as readers do not block writers and a writer does not block readers. Reading and writing can proceed concurrently.
* Simply set `journal_mode` to WAL
* Separate file locks and write locks. Read locks are unnecessary as WAL mode can handle concurrent readers.
=> Enable SQLite WAL mode and remove read locks

database/db.go
* The default for `synchronous` is full, which means every single update has to wait for `fsync`.
* The default of -1 for `journal_size_limit` means that there is no limit, so this disk file will grow in size indefinitely. This is not what we want.
* Switch to normal synchronization. Normal is still completely corruption safe in WAL mode, and means only WAL checkpoints have to wait for `fsync`.
* Set `journal_size_limit` to a reasonable amount. The more data is in the journal file, the faster SQLite will be (generally). However, we also don’t want it to be too big, as this can start to negatively impact read performance.
=> Relax the synchronization mode

README.md, m3u/middlewares.go, m3u/parser.go
* Some providers add country codes and other characters to channel names, this makes it possible to make them cleaner.
* Apply go regexp makes it easy to filter unwanted chars.
1. Tested different regexp on playlists.
=> add char filter function

mp4_handler.go
* There are edge cases where an idle connection (while waiting for EOF) is sustained indefinitely.
* By having a default buffer, the contents can be checked to see if it's empty or not. If it's empty for a certain timeout period, then cancel the HTTP context altogether and close the connection.
=> Add timeout and use HTTP context with cancel

m3u/parser.go
* Attributes with values that have commas break the parser. (#58)
* By removing all attributes-values pairs before splitting the string with comma as delimiter, the first comma split is guaranteed to be the channel title.
=> Properly remove key-value pairs when comma splitting

README.md, m3u/generate.go, m3u/m3u_test.go, m3u/parser.go, main.go, main_test.go, mp4_handler.go, stream_handler.go
* Issue #60 
* Using the same file extension as the source M3U will ensure that apps that use the file extensions will have the same behavior as the source M3U.
=> Use source M3U's file extension for streams

README.md, m3u/parser.go, main_test.go
* Have separate group filter for each m3u file instead of one for all.
* Follow same pattern as for M3U_MAX_CONCURRENCY_X and M3U_URL_X
1. Tested on multiple m3u files, with different group filters.
=> Separate group filter for each m3u file

README.md, stream_handler.go
* Remove load-balancing algo options and make the default (and only) mode smarter.
* LB algos like round-robin are "stateful" which will require too much effort for its use and purposes.
1.
=> Remove load-balancer modes

stream_handler.go
* When switching from one source to another, the returned Content-Length header becomes stale and produces the "wrote more than the declared Content-Length" error. Not returning any content-length headers would fix this.
* 
1.
=> Ignore content-length header from source

README.md, database/db.go, m3u/generate.go, m3u/m3u_test.go
Fixed the channel sorting and added channel numbers. Now when it generates the new m3u it adds the channel numbers in various formats again so Emby can understand it. And it will now at all times sort the m3u from the lowest channel id to the highest instead of random.
so it works
i builded the docker container on my pc and pushed it to dockerhub and tested it on my setup and it works.
* [ x] I have performed a self-review of my code
* [ x] I've added documentation about this change to the README.
* [ x] I've not introduced breaking changes.
=> fix sorting

database/concurrency_utils.go, m3u/parser.go, main.go, stream_handler.go
* This is probably the source of most bugs for the load balancer so far. Some parts of the code were confusing due to the term "index" which implies that the value starts from 0 but actually starts from 1.
* Make all values start from 0 then +1 when printing to a log and for env vars to prevent breaking changes from config.
1.
=> Use base 0 for m3u index

README.md, m3u/parser.go
* Fix spawning too much workers for parsing causing some workers to crash due to low resources (#72)
* Use a worker pool pattern to limit the number of goroutines
1.
=> Use a worker pool pattern to limit the number of goroutines

README.md, database/db.go, database/types.go, m3u/generate.go, m3u/middlewares.go, m3u/parser.go
* #68 introduced a regression for m3u providers that don't use tvg-id.
* Add `SORTING_KEY` env var to set the tag to be used for sorting.
1.
=> Add option to change key being used by the database sort

database/database_test.go, database/db.go, database/types.go, go.mod, go.sum, m3u/generate.go, m3u/m3u_test.go, m3u/parser.go, main_test.go, stream_handler.go, utils/url.go, utils/utils_test.go
* Since redis uses colons ":" as a "special" character for keys, slugifying the title to be used is needed.
* High resource usage was observed on large M3Us especially on query and insert.
* For M3U parsing, assume proper format and all values of tags are within double quotation marks.
* Use pipelines for Redis queries.
* Slugify stream titles
1.
=> Optimize Redis queries and inserts

database/database_test.go, database/db.go, database/types.go, m3u/generate.go, m3u/m3u_test.go, m3u/parser.go, main_test.go, stream_handler.go, utils/env.go
* Using the index number used in env var configs directly would be much easier for the load balancer
* The usage of an array was initially designed due to the use of SQLite rather than a KV database like Redis.
* Simplify StreamURL data structure to map[int]string.
1.
=> Use map for m3u index instead of an array

database/db.go, m3u/generate.go, m3u/parser.go, stream_handler.go
=> Add more debug logs

.github/workflows/pr-build.yml, stream_handler.go, utils/env.go
=> Fix M3U index fetching to base 0

database/database_test.go, database/db.go, m3u/generate.go, m3u/m3u_test.go, main.go, main_test.go
* Chunking and parallelizing an array of streams from Redis breaks the sort order
* 
1.
=> Use channels for streams and remove chunking on M3U generation

README.md, stream_handler.go
=> Add MAX_RETRIES to specify max retry loop quantity

database/db.go
=> Add zero padding on integer/float tvg-id or tvg-chno values to fix sorting

stream_handler.go, utils/url.go
=> Prevent retry on EOF if mimetype is `application/x-mpegurl`

proxy/stream_handler.go
=> Convert relative urls from m3u8 streams to absolute paths on-the-fly

Dockerfile, README.md, entrypoint.sh, m3u/generate.go
=> Add PUID/PGID setting on container runtime

m3u/generate.go, m3u/m3u_test.go
=> Exclude optional tvg tags if source M3U doesn't have them

README.md, m3u/parser.go
* #153 
| ENV VAR                     | Description                                              | Default Value | Possible Values                                |
|-----------------------------|----------------------------------------------------------|---------------|------------------------------------------------|
| RETRY_WAIT | Set a wait time before retrying (looping) across all M3Us on stream initialization error. | 0 | Any integer greater than or equal 0 |
1.
=> Add RETRY_WAIT feature to set a wait time on the retry loop

handlers/stream_handler.go, proxy/load_balancer.go, store/sessions.go, updater/updater.go, utils/fingerprint.go
=> Add a memory session to retain tested indexes across requests

go.mod, go.sum, handlers/stream_handler.go, proxy/load_balancer.go, proxy/proxy_stream.go, store/concurrency.go, store/downloader.go, store/parser.go, store/sessions.go, store/streams.go, store/types.go, tests/proxy_test.go, updater/updater.go, utils/env.go, utils/m3u_path.go
=> Add subindex for inter-m3u duplicates

.gitignore, Dockerfile, README.md
Please at least use the Dockerfile in this.  It just changes to FQDN's for the image registries.  When using Podman it is required to use valid registries, which means it needs FQDNs
Also corrected the readme for the default sort... which is by title, not tvg-id
=> Dockerfile and Readme Corrections

README.md, docker-compose.yaml, updater/updater.go
* `CACHE_ON_SYNC` is now required and should be removed as an env var option.
* 
1.
=> remove CACHE_ON_SYNC from existence
