sonroyaalmerol/m3u-stream-merger-proxy

- Dockerfile
- database/database_test.go
- database/db.go
- database/types.go
- go.mod
- go.sum
- m3u/generate.go
- m3u/global.go
- m3u/parser.go
- m3u/save.go
Using a JSON file for database is not scalable and performant, might as well use SQLite.
> Switch to SQLite

- Dockerfile
- README.md
- database/database_test.go
- database/db.go
- database/redis.go
- database/types.go
- entrypoint.sh
- go.mod
- go.sum
- m3u/generate.go
- m3u/m3u_test.go
- m3u/parser.go
- main.go
- mp4_handler.go
> Add M3U_MAX_CONCURRENCY_X env variable

- mp4_handler.go
Fixes concurrency count not matching if it fall backs to connection check mode
> Set selectedUrl in connection check mode

- database/db.go
- m3u/parser.go
- mp4_handler.go
> Fix concurrency limit not persisting across different requests

- mp4_handler.go
> Log current concurrent connections on update

- mp4_handler.go
* Incorrect implementation of HTTP timeouts as streams are supposed to be long-lived connections.
* Revert
> Revert HTTP timeouts to default

- main.go
> Ensure nextDb is garbage after swapping

- main.go
Reverts sonroyaalmerol/m3u-stream-merger-proxy#43
> Revert "Ensure nextDb is garbage after swapping"

- .github/workflows/linting.yml
> Revert golangci-lint caching

- Dockerfile
> Fix gcc build dependencies

- mp4_handler.go
Reverts sonroyaalmerol/m3u-stream-merger-proxy#55
> Revert "Add timeout and use HTTP context with cancel"

- mp4_handler.go
> Add timeout and use HTTP context with cancel

- stream_handler.go
> Rework load balancing connection algorithm

- stream_handler.go
> fix: replace break with return

- stream_handler.go
> Skip previous URL when load balancing again

- stream_handler.go
* Ensure the goroutine within the for loops are receiving non-stale values.
* 
1.
> Fix load balancer loop bugs

- Dockerfile
- database/db.go
- m3u/m3u_test.go
> Add test cases for no tvg-id entries

- stream_handler.go
> Track previous indexes to avoid endless loops

- m3u/m3u_test.go
- m3u/parser.go
* Adds support for `file://` URIs as M3U source.
* Closes #78 
* 
1.
> Add local file support

- database/cache.go
- database/db.go
- main.go
> Add in-memory cache and chunking on Redis query

- README.md
- main.go
- main_test.go
> Add option to cache streams in-memory after syncing

- database/db.go
> Fix redis WRONGTYPE error on stream

- stream_handler.go
- utils/url.go
> Consider success if a playlist file reaches EOF

- stream_handler.go
> Clear buffer and flush out writer on return

- README.md
- m3u/parser.go
- stream_handler.go
> Add timeout duration before stream is considered down

- stream_handler.go
> Add backoff on retry timeout

- .github/workflows/pr-build.yml
- stream_handler.go
> Use HTTP context within stream goroutine

- Dockerfile
Final container size down to 19.6M
1. Just rebuild your local container and run it
> shrink down final container

- database/db.go
- stream_handler.go
> Fix clear concurrencies function

- Dockerfile
> Exclude arm64 from Go tests in Dockerfile temporarily

- stream_handler.go
- utils/url.go
> Add list of possible m3u mimetypes to check

- utils/url.go
> Include file extensions to determine stream type

- .github/workflows/pr-build.yml
- .github/workflows/pr-publish.yml
> Fix PR publish workflow

- .github/workflows/pr-publish.yml
> Fix PR workflow result-encoding

- m3u/parser.go
- stream_handler.go
- utils/http.go
> Support non-GET request forwarding and include all HTTP headers excluding Content-Length

- m3u/generate.go
- m3u/parser.go
- main.go
> Add file cache layer for M3U generate

- stream_handler.go
> Handle all non-GET methods as transparent proxy

- stream_handler.go
> Allow STREAM_TIMEOUT=0

- .github/workflows/linting.yml
- database/db.go
- m3u/generate.go
- updater/updater.go
> Clear db before executing save to db on sync to remove stale streams

- m3u/generate.go
- updater/updater.go
- utils/http.go
> Remove unused wg from cache_on_sync workflow

- database/concurrency_utils.go
- database/db.go
- m3u/downloader.go
- m3u/generate.go
- m3u/middlewares.go
- m3u/parser.go
- main.go
- proxy/proxy_test.go
- proxy/stream_handler.go
- updater/updater.go
- utils/logs.go
- utils/url.go
> Convert all generic logs to use safe log

- README.md
- m3u/filters.go
- m3u/middlewares.go
- m3u/parser.go
- utils/env.go
> Add include/exclude for groups and titles as filter options

- m3u/m3u_test.go
- m3u/parser.go
> Parser support for M3Us with extra EXT tags

- utils/env.go
> Use maps for filter env cache

- proxy/stream_handler.go
- utils/http.go
> Immediately close response body on client disconnect

- Dockerfile
- README.md
- main.go
> Add option to change internal port

- handlers/stream_handler.go
- proxy/load_balancer.go
- proxy/proxy_stream.go
- store/concurrency.go
* mainly to fix handling of unexpected EOF but may fix #197 
* 
1.
> Fix orphaned goroutines on client disconnects

- handlers/stream_handler.go
- proxy/proxy_stream.go
> Use manual elapsed timer instead of timer channels

- proxy/proxy_stream.go
> Fix err panic on runtime while proxying stream

- proxy/stream/shared_buffer.go
> Ensure chunks are reset and remove buffer swapping mechanism

- source_processor/m3u_manager.go
- source_processor/parser.go
- source_processor/source_processor_test.go
> merge attributes if existing one is empty

- source_processor/m3u_manager.go
- source_processor/source_processor_test.go
> ensure latest attributes are used during m3u finalization

- handlers/stream_http.go
- proxy/stream/shared_buffer.go
- proxy/stream/stream_handler.go
- source_processor/m3u_manager.go
> ensure each requests refer to different coordinators for different request URLs

- source_processor/m3u_manager.go
- source_processor/source_processor.go
- source_processor/source_processor_test.go
> wait for initial m3u generation before responding

- handlers/m3u_http.go
> ensure creds expires on local TZ

- proxy/stream/shared_buffer.go
> set stale logs to debug

- handlers/passthrough_http.go
- main.go
- sourceproc/sourceproc_test.go
- utils/middlewares.go
> add passthrough proxy for logo url

- config/config.go
- sourceproc/downloader.go
- sourceproc/processor.go
> properly handle source m3u failure and implement fallback

- sourceproc/downloader.go
> validate source being parsed is an M3U file

- Dockerfile
- go.mod
- go.sum
- handlers/stream_http.go
- integration_test.go
- proxy/client/client.go
- proxy/loadbalancer/instance.go
- proxy/loadbalancer/loadbalancer_test.go
- sourceproc/filter.go
- sourceproc/helpers.go
- sourceproc/parser.go
- sourceproc/processor.go
- sourceproc/slug.go
- sourceproc/sorting.go
- sourceproc/stream_info.go
- utils/safemap/xsync.go
> implement xsync on streaminfo urls map to avoid race conditions
